"""sprint4_conformance_init

Revision ID: 2a4c95ff1c79
Revises: 7d706cb199f3
Create Date: 2026-06-16 17:49:05.166353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4c95ff1c79'
down_revision: Union[str, Sequence[str], None] = '7d706cb199f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_activity_name'), 'emission_factors', ['activity_name'], unique=False)
    op.create_index(op.f('ix_emission_factors_created_at'), 'emission_factors', ['created_at'], unique=False)
    op.create_index(op.f('ix_emission_factors_source_name'), 'emission_factors', ['source_name'], unique=False)
    op.create_index(op.f('ix_emission_factors_tenant_id'), 'emission_factors', ['tenant_id'], unique=False)
    op.create_table('reference_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_model_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_definition', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_model_id'], ['reference_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ref_model_tenant_workspace', 'reference_models', ['tenant_id', 'workspace_id'], unique=False)
    op.create_index('idx_ref_model_workspace_project', 'reference_models', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_reference_models_created_at'), 'reference_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_reference_models_project_id'), 'reference_models', ['project_id'], unique=False)
    op.create_index(op.f('ix_reference_models_tenant_id'), 'reference_models', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reference_models_workspace_id'), 'reference_models', ['workspace_id'], unique=False)
    op.create_table('carbon_attributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=False),
    sa.Column('emissions', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_carb_attr_analysis_activity', 'carbon_attributions', ['analysis_id', 'activity_name'], unique=False)
    op.create_index('idx_carb_attr_tenant_workspace', 'carbon_attributions', ['tenant_id', 'workspace_id'], unique=False)
    op.create_index('idx_carb_attr_workspace_project', 'carbon_attributions', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_carbon_attributions_activity_name'), 'carbon_attributions', ['activity_name'], unique=False)
    op.create_index(op.f('ix_carbon_attributions_analysis_id'), 'carbon_attributions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_carbon_attributions_created_at'), 'carbon_attributions', ['created_at'], unique=False)
    op.create_index(op.f('ix_carbon_attributions_project_id'), 'carbon_attributions', ['project_id'], unique=False)
    op.create_index(op.f('ix_carbon_attributions_tenant_id'), 'carbon_attributions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_carbon_attributions_workspace_id'), 'carbon_attributions', ['workspace_id'], unique=False)
    op.create_table('conformance_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('fitness_score', sa.Float(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=False),
    sa.Column('carbon_fitness_score', sa.Float(), nullable=False),
    sa.Column('carbon_budget', sa.Float(), nullable=False),
    sa.Column('actual_emissions', sa.Float(), nullable=False),
    sa.Column('excess_emissions', sa.Float(), nullable=False),
    sa.Column('budget_exceeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conf_res_tenant_workspace', 'conformance_results', ['tenant_id', 'workspace_id'], unique=False)
    op.create_index('idx_conf_res_workspace_project', 'conformance_results', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_conformance_results_analysis_id'), 'conformance_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_conformance_results_created_at'), 'conformance_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_conformance_results_project_id'), 'conformance_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_conformance_results_tenant_id'), 'conformance_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conformance_results_workspace_id'), 'conformance_results', ['workspace_id'], unique=False)
    op.create_table('emission_hotspots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('emissions', sa.Float(), nullable=False),
    sa.Column('contribution_percentage', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hotspot_analysis_activity', 'emission_hotspots', ['analysis_id', 'activity_name'], unique=False)
    op.create_index('idx_hotspot_tenant_workspace', 'emission_hotspots', ['tenant_id', 'workspace_id'], unique=False)
    op.create_index('idx_hotspot_workspace_project', 'emission_hotspots', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_emission_hotspots_activity_name'), 'emission_hotspots', ['activity_name'], unique=False)
    op.create_index(op.f('ix_emission_hotspots_analysis_id'), 'emission_hotspots', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_emission_hotspots_created_at'), 'emission_hotspots', ['created_at'], unique=False)
    op.create_index(op.f('ix_emission_hotspots_project_id'), 'emission_hotspots', ['project_id'], unique=False)
    op.create_index(op.f('ix_emission_hotspots_tenant_id'), 'emission_hotspots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_emission_hotspots_workspace_id'), 'emission_hotspots', ['workspace_id'], unique=False)
    op.create_table('conformance_deviations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('deviation_type', sa.String(), nullable=False),
    sa.Column('expected_transition', sa.String(), nullable=True),
    sa.Column('actual_transition', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['conformance_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deviation_analysis_activity', 'conformance_deviations', ['analysis_id', 'activity_name'], unique=False)
    op.create_index('idx_deviation_tenant_workspace', 'conformance_deviations', ['tenant_id', 'workspace_id'], unique=False)
    op.create_index('idx_deviation_workspace_project', 'conformance_deviations', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_activity_name'), 'conformance_deviations', ['activity_name'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_analysis_id'), 'conformance_deviations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_created_at'), 'conformance_deviations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_project_id'), 'conformance_deviations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_result_id'), 'conformance_deviations', ['result_id'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_tenant_id'), 'conformance_deviations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conformance_deviations_workspace_id'), 'conformance_deviations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_conformance_deviations_workspace_id'), table_name='conformance_deviations')
    op.drop_index(op.f('ix_conformance_deviations_tenant_id'), table_name='conformance_deviations')
    op.drop_index(op.f('ix_conformance_deviations_result_id'), table_name='conformance_deviations')
    op.drop_index(op.f('ix_conformance_deviations_project_id'), table_name='conformance_deviations')
    op.drop_index(op.f('ix_conformance_deviations_created_at'), table_name='conformance_deviations')
    op.drop_index(op.f('ix_conformance_deviations_analysis_id'), table_name='conformance_deviations')
    op.drop_index(op.f('ix_conformance_deviations_activity_name'), table_name='conformance_deviations')
    op.drop_index('idx_deviation_workspace_project', table_name='conformance_deviations')
    op.drop_index('idx_deviation_tenant_workspace', table_name='conformance_deviations')
    op.drop_index('idx_deviation_analysis_activity', table_name='conformance_deviations')
    op.drop_table('conformance_deviations')
    op.drop_index(op.f('ix_emission_hotspots_workspace_id'), table_name='emission_hotspots')
    op.drop_index(op.f('ix_emission_hotspots_tenant_id'), table_name='emission_hotspots')
    op.drop_index(op.f('ix_emission_hotspots_project_id'), table_name='emission_hotspots')
    op.drop_index(op.f('ix_emission_hotspots_created_at'), table_name='emission_hotspots')
    op.drop_index(op.f('ix_emission_hotspots_analysis_id'), table_name='emission_hotspots')
    op.drop_index(op.f('ix_emission_hotspots_activity_name'), table_name='emission_hotspots')
    op.drop_index('idx_hotspot_workspace_project', table_name='emission_hotspots')
    op.drop_index('idx_hotspot_tenant_workspace', table_name='emission_hotspots')
    op.drop_index('idx_hotspot_analysis_activity', table_name='emission_hotspots')
    op.drop_table('emission_hotspots')
    op.drop_index(op.f('ix_conformance_results_workspace_id'), table_name='conformance_results')
    op.drop_index(op.f('ix_conformance_results_tenant_id'), table_name='conformance_results')
    op.drop_index(op.f('ix_conformance_results_project_id'), table_name='conformance_results')
    op.drop_index(op.f('ix_conformance_results_created_at'), table_name='conformance_results')
    op.drop_index(op.f('ix_conformance_results_analysis_id'), table_name='conformance_results')
    op.drop_index('idx_conf_res_workspace_project', table_name='conformance_results')
    op.drop_index('idx_conf_res_tenant_workspace', table_name='conformance_results')
    op.drop_table('conformance_results')
    op.drop_index(op.f('ix_carbon_attributions_workspace_id'), table_name='carbon_attributions')
    op.drop_index(op.f('ix_carbon_attributions_tenant_id'), table_name='carbon_attributions')
    op.drop_index(op.f('ix_carbon_attributions_project_id'), table_name='carbon_attributions')
    op.drop_index(op.f('ix_carbon_attributions_created_at'), table_name='carbon_attributions')
    op.drop_index(op.f('ix_carbon_attributions_analysis_id'), table_name='carbon_attributions')
    op.drop_index(op.f('ix_carbon_attributions_activity_name'), table_name='carbon_attributions')
    op.drop_index('idx_carb_attr_workspace_project', table_name='carbon_attributions')
    op.drop_index('idx_carb_attr_tenant_workspace', table_name='carbon_attributions')
    op.drop_index('idx_carb_attr_analysis_activity', table_name='carbon_attributions')
    op.drop_table('carbon_attributions')
    op.drop_index(op.f('ix_reference_models_workspace_id'), table_name='reference_models')
    op.drop_index(op.f('ix_reference_models_tenant_id'), table_name='reference_models')
    op.drop_index(op.f('ix_reference_models_project_id'), table_name='reference_models')
    op.drop_index(op.f('ix_reference_models_created_at'), table_name='reference_models')
    op.drop_index('idx_ref_model_workspace_project', table_name='reference_models')
    op.drop_index('idx_ref_model_tenant_workspace', table_name='reference_models')
    op.drop_table('reference_models')
    op.drop_index(op.f('ix_emission_factors_tenant_id'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_source_name'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_created_at'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_activity_name'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
