"""sprint3_process_mining_init

Revision ID: 7d706cb199f3
Revises: 
Create Date: 2026-06-16 17:10:01.224997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d706cb199f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('parent_analysis_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_analysis_id'], ['process_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_process_analysis_dataset_version', 'process_analyses', ['dataset_id', 'analysis_version'], unique=False)
    op.create_index('idx_process_analysis_project_dataset', 'process_analyses', ['project_id', 'dataset_id'], unique=False)
    op.create_index('idx_process_analysis_tenant_workspace', 'process_analyses', ['tenant_id', 'workspace_id'], unique=False)
    op.create_index('idx_process_analysis_workspace_project', 'process_analyses', ['workspace_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_process_analyses_created_at'), 'process_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_analyses_dataset_id'), 'process_analyses', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_process_analyses_project_id'), 'process_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_process_analyses_status'), 'process_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_process_analyses_tenant_id'), 'process_analyses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_process_analyses_workspace_id'), 'process_analyses', ['workspace_id'], unique=False)
    op.create_table('process_bottlenecks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('average_wait_time', sa.Float(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_bottlenecks_analysis_id'), 'process_bottlenecks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_process_bottlenecks_created_at'), 'process_bottlenecks', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_bottlenecks_project_id'), 'process_bottlenecks', ['project_id'], unique=False)
    op.create_index(op.f('ix_process_bottlenecks_tenant_id'), 'process_bottlenecks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_process_bottlenecks_workspace_id'), 'process_bottlenecks', ['workspace_id'], unique=False)
    op.create_table('process_graphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('graph_type', sa.String(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_graphs_analysis_id'), 'process_graphs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_process_graphs_created_at'), 'process_graphs', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_graphs_graph_type'), 'process_graphs', ['graph_type'], unique=False)
    op.create_index(op.f('ix_process_graphs_project_id'), 'process_graphs', ['project_id'], unique=False)
    op.create_index(op.f('ix_process_graphs_tenant_id'), 'process_graphs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_process_graphs_workspace_id'), 'process_graphs', ['workspace_id'], unique=False)
    op.create_table('process_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('object_type_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_models_analysis_id'), 'process_models', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_process_models_created_at'), 'process_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_models_project_id'), 'process_models', ['project_id'], unique=False)
    op.create_index(op.f('ix_process_models_tenant_id'), 'process_models', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_process_models_workspace_id'), 'process_models', ['workspace_id'], unique=False)
    op.create_table('process_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('activity_sequence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['process_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_variants_analysis_id'), 'process_variants', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_process_variants_created_at'), 'process_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_variants_project_id'), 'process_variants', ['project_id'], unique=False)
    op.create_index(op.f('ix_process_variants_tenant_id'), 'process_variants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_process_variants_workspace_id'), 'process_variants', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_variants_workspace_id'), table_name='process_variants')
    op.drop_index(op.f('ix_process_variants_tenant_id'), table_name='process_variants')
    op.drop_index(op.f('ix_process_variants_project_id'), table_name='process_variants')
    op.drop_index(op.f('ix_process_variants_created_at'), table_name='process_variants')
    op.drop_index(op.f('ix_process_variants_analysis_id'), table_name='process_variants')
    op.drop_table('process_variants')
    op.drop_index(op.f('ix_process_models_workspace_id'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_tenant_id'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_project_id'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_created_at'), table_name='process_models')
    op.drop_index(op.f('ix_process_models_analysis_id'), table_name='process_models')
    op.drop_table('process_models')
    op.drop_index(op.f('ix_process_graphs_workspace_id'), table_name='process_graphs')
    op.drop_index(op.f('ix_process_graphs_tenant_id'), table_name='process_graphs')
    op.drop_index(op.f('ix_process_graphs_project_id'), table_name='process_graphs')
    op.drop_index(op.f('ix_process_graphs_graph_type'), table_name='process_graphs')
    op.drop_index(op.f('ix_process_graphs_created_at'), table_name='process_graphs')
    op.drop_index(op.f('ix_process_graphs_analysis_id'), table_name='process_graphs')
    op.drop_table('process_graphs')
    op.drop_index(op.f('ix_process_bottlenecks_workspace_id'), table_name='process_bottlenecks')
    op.drop_index(op.f('ix_process_bottlenecks_tenant_id'), table_name='process_bottlenecks')
    op.drop_index(op.f('ix_process_bottlenecks_project_id'), table_name='process_bottlenecks')
    op.drop_index(op.f('ix_process_bottlenecks_created_at'), table_name='process_bottlenecks')
    op.drop_index(op.f('ix_process_bottlenecks_analysis_id'), table_name='process_bottlenecks')
    op.drop_table('process_bottlenecks')
    op.drop_index(op.f('ix_process_analyses_workspace_id'), table_name='process_analyses')
    op.drop_index(op.f('ix_process_analyses_tenant_id'), table_name='process_analyses')
    op.drop_index(op.f('ix_process_analyses_status'), table_name='process_analyses')
    op.drop_index(op.f('ix_process_analyses_project_id'), table_name='process_analyses')
    op.drop_index(op.f('ix_process_analyses_dataset_id'), table_name='process_analyses')
    op.drop_index(op.f('ix_process_analyses_created_at'), table_name='process_analyses')
    op.drop_index('idx_process_analysis_workspace_project', table_name='process_analyses')
    op.drop_index('idx_process_analysis_tenant_workspace', table_name='process_analyses')
    op.drop_index('idx_process_analysis_project_dataset', table_name='process_analyses')
    op.drop_index('idx_process_analysis_dataset_version', table_name='process_analyses')
    op.drop_table('process_analyses')
    # ### end Alembic commands ###
