"""sprint4_parent_model_index

Revision ID: ebf871aa430e
Revises: c90d7b77788b
Create Date: 2026-06-16 18:43:44.800346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf871aa430e'
down_revision: Union[str, Sequence[str], None] = 'c90d7b77788b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reference_models_parent_model_id'), 'reference_models', ['parent_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_models_parent_model_id'), table_name='reference_models')
    # ### end Alembic commands ###
