"""sprint5_esg_foundation

Revision ID: ff870c70b120
Revises: ebf871aa430e
Create Date: 2026-06-16 19:35:43.626657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff870c70b120'
down_revision: Union[str, Sequence[str], None] = 'ebf871aa430e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_frameworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework_name', sa.String(), nullable=False),
    sa.Column('framework_version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_frameworks_framework_name'), 'esg_frameworks', ['framework_name'], unique=True)
    op.create_table('esg_kpi_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kpi_code', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('calculation_method', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_kpi_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_kpi_id'], ['esg_kpi_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_esg_kpi_code_version', 'esg_kpi_definitions', ['kpi_code', 'version'], unique=False)
    op.create_index(op.f('ix_esg_kpi_definitions_category'), 'esg_kpi_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_esg_kpi_definitions_kpi_code'), 'esg_kpi_definitions', ['kpi_code'], unique=False)
    op.create_index(op.f('ix_esg_kpi_definitions_parent_kpi_id'), 'esg_kpi_definitions', ['parent_kpi_id'], unique=False)
    op.create_index(op.f('ix_esg_kpi_definitions_tenant_id'), 'esg_kpi_definitions', ['tenant_id'], unique=False)
    op.create_table('esg_scoring_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('environmental_weight', sa.Float(), nullable=False),
    sa.Column('social_weight', sa.Float(), nullable=False),
    sa.Column('governance_weight', sa.Float(), nullable=False),
    sa.Column('kpi_weights', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_scoring_profiles_tenant_id'), 'esg_scoring_profiles', ['tenant_id'], unique=False)
    op.create_table('esg_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('scoring_profile_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('environmental_score', sa.Float(), nullable=False),
    sa.Column('social_score', sa.Float(), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scoring_profile_id'], ['esg_scoring_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_scores_period'), 'esg_scores', ['period'], unique=False)
    op.create_index(op.f('ix_esg_scores_tenant_id'), 'esg_scores', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_esg_scores_workspace_id'), 'esg_scores', ['workspace_id'], unique=False)
    op.create_table('framework_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('kpi_definition_id', sa.UUID(), nullable=False),
    sa.Column('framework_section', sa.String(), nullable=False),
    sa.Column('framework_principle', sa.String(), nullable=True),
    sa.Column('framework_question', sa.String(), nullable=False),
    sa.Column('reporting_category', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['esg_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_definition_id'], ['esg_kpi_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_framework_kpi_mapping', 'framework_mappings', ['framework_id', 'kpi_definition_id'], unique=False)
    op.create_index(op.f('ix_framework_mappings_framework_id'), 'framework_mappings', ['framework_id'], unique=False)
    op.create_index(op.f('ix_framework_mappings_kpi_definition_id'), 'framework_mappings', ['kpi_definition_id'], unique=False)
    op.create_table('esg_kpi_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_definition_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_definition_id'], ['esg_kpi_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_kpi_values_kpi_definition_id'), 'esg_kpi_values', ['kpi_definition_id'], unique=False)
    op.create_index(op.f('ix_esg_kpi_values_period'), 'esg_kpi_values', ['period'], unique=False)
    op.create_index(op.f('ix_esg_kpi_values_project_id'), 'esg_kpi_values', ['project_id'], unique=False)
    op.create_index(op.f('ix_esg_kpi_values_tenant_id'), 'esg_kpi_values', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_esg_kpi_values_workspace_id'), 'esg_kpi_values', ['workspace_id'], unique=False)
    op.create_table('esg_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_value_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_description', sa.String(), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=True),
    sa.Column('evidence_file_path', sa.String(), nullable=True),
    sa.Column('cryptographic_hash', sa.String(), nullable=True),
    sa.Column('calculation_steps', sa.JSON(), nullable=False),
    sa.Column('lineage_path', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('audited_by', sa.UUID(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_value_id'], ['esg_kpi_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_evidence_kpi_value_id'), 'esg_evidence', ['kpi_value_id'], unique=False)
    op.create_index(op.f('ix_esg_evidence_source_entity_type'), 'esg_evidence', ['source_entity_type'], unique=False)
    op.create_index(op.f('ix_esg_evidence_tenant_id'), 'esg_evidence', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esg_evidence_tenant_id'), table_name='esg_evidence')
    op.drop_index(op.f('ix_esg_evidence_source_entity_type'), table_name='esg_evidence')
    op.drop_index(op.f('ix_esg_evidence_kpi_value_id'), table_name='esg_evidence')
    op.drop_table('esg_evidence')
    op.drop_index(op.f('ix_esg_kpi_values_workspace_id'), table_name='esg_kpi_values')
    op.drop_index(op.f('ix_esg_kpi_values_tenant_id'), table_name='esg_kpi_values')
    op.drop_index(op.f('ix_esg_kpi_values_project_id'), table_name='esg_kpi_values')
    op.drop_index(op.f('ix_esg_kpi_values_period'), table_name='esg_kpi_values')
    op.drop_index(op.f('ix_esg_kpi_values_kpi_definition_id'), table_name='esg_kpi_values')
    op.drop_table('esg_kpi_values')
    op.drop_index(op.f('ix_framework_mappings_kpi_definition_id'), table_name='framework_mappings')
    op.drop_index(op.f('ix_framework_mappings_framework_id'), table_name='framework_mappings')
    op.drop_index('idx_framework_kpi_mapping', table_name='framework_mappings')
    op.drop_table('framework_mappings')
    op.drop_index(op.f('ix_esg_scores_workspace_id'), table_name='esg_scores')
    op.drop_index(op.f('ix_esg_scores_tenant_id'), table_name='esg_scores')
    op.drop_index(op.f('ix_esg_scores_period'), table_name='esg_scores')
    op.drop_table('esg_scores')
    op.drop_index(op.f('ix_esg_scoring_profiles_tenant_id'), table_name='esg_scoring_profiles')
    op.drop_table('esg_scoring_profiles')
    op.drop_index(op.f('ix_esg_kpi_definitions_tenant_id'), table_name='esg_kpi_definitions')
    op.drop_index(op.f('ix_esg_kpi_definitions_parent_kpi_id'), table_name='esg_kpi_definitions')
    op.drop_index(op.f('ix_esg_kpi_definitions_kpi_code'), table_name='esg_kpi_definitions')
    op.drop_index(op.f('ix_esg_kpi_definitions_category'), table_name='esg_kpi_definitions')
    op.drop_index('idx_esg_kpi_code_version', table_name='esg_kpi_definitions')
    op.drop_table('esg_kpi_definitions')
    op.drop_index(op.f('ix_esg_frameworks_framework_name'), table_name='esg_frameworks')
    op.drop_table('esg_frameworks')
    # ### end Alembic commands ###
